#!/bin/sh

exec < /dev/tty

gitdir=`git rev-parse --git-dir`/hooks/;
projhooks=`git rev-parse --show-toplevel`/hooks/;

file=`echo $0 | grep -o '[^\/]*$'`.js

# Executa o script node da pasta .git/hooks se ele existir
if [ -e ${gitdir}${file} ]; then
	echo
	echo "Executando hook ${gitdir}${file} ..."
	echo
	node ${gitdir}${file} $0 $1 $2 $3 || exit 1
fi

# Executa o script node da pasta hooks na raíz do projeto se ele existir
if [ -e ${projhooks}${file} ]; then
	echo
	echo "Executando hook ${projhooks}${file} ..."
	echo
	node ${projhooks}${file} $0 $1 $2 $3 || exit 1
fi

